config/routes.rb
Rails.application.routes.draw do
  root to: 'comic_characters#index'

  resources :comic_characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic_character.rb
class ComicCharacter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def filter(relation)
    return relation unless filter_params.any?

    relation.where(filter_params)
  end

  def sort(relation)
    relation.order(sort_instructions)
  end

  def sort_instructions
    if sort_params.key?(:attribute) && sort_params.key?(:direction)
      { sort_params[:attribute] => sort_params[:direction] }
    else
      sort_params.transform_values { |v| v.remove('ending') }
    end
  end

  def filter_params
    params.fetch(:filter, {}).to_unsafe_hash
  end

  def sort_params
    params.fetch(:sort, { id: 'ascending' }).to_unsafe_hash
  end
  helper_method :sort_params
end

app/controllers/comic_characters_controller.rb
class ComicCharactersController < ApplicationController
  before_action :set_comic_character, only: [:show, :edit, :update, :destroy]

  def index
    @comic_characters = sort(filter(ComicCharacter.all)).limit(100)
  end

  def show
  end

  def new
    @comic_character = ComicCharacter.new
  end

  def edit
  end

  def create
    @comic_character = ComicCharacter.new(comic_character_params)

    respond_to do |format|
      if @comic_character.save
        format.html { redirect_to @comic_character, notice: 'Comic character was successfully created.' }
        format.json { render :show, status: :created, location: @comic_character }
      else
        format.html { render :new }
        format.json { render json: @comic_character.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comic_character.update(comic_character_params)
        format.html { redirect_to @comic_character, notice: 'Comic character was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic_character }
      else
        format.html { render :edit }
        format.json { render json: @comic_character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comic_character.destroy
    respond_to do |format|
      format.html { redirect_to comic_characters_url, notice: 'Comic character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_comic_character
    @comic_character = ComicCharacter.find(params[:id])
  end

  def comic_character_params
    params.require(:comic_character).permit(:publisher, :real_name, :alias, :url, :appearances, :alive, :gender, :identity_type, :alignment, :intro_in)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comic_characters_helper.rb
module ComicCharactersHelper
end

app/helpers/form_for_helper.rb
module FormForHelper
  def form_for_object_from_param(param)
    form_for_params = params.fetch(param, {})
    form_for_requirements = { model_name: { param_key: param } }

    JSON.parse(form_for_params.merge(form_for_requirements).to_json,
               object_class: OpenStruct)
  end
end

app/helpers/i18n_helper.rb
# frozen_string_literal: true

module I18nHelper
  # Attempt to make an I18n translation,
  # but return `nil` if no translation found
  def translate(path, scope = nil)
    I18n.translate!(path, scope: scope)
  rescue I18n::MissingTranslationData
    nil
  end

  # Attempt to make an I18n translation,
  # but return `true` or `false` if no translation found
  def translate_boolean(boolean)
    I18n.translate!(boolean)
  rescue I18n::MissingTranslationData
    boolean.to_s
  end

  # Attempt to make an I18n localization,
  # but return a localized date-string with '—' in the place of numbers
  # if no localization found
  def localize_date(date)
    if date.nil?
      return I18n.localize(Date.new)
                 .gsub('01', '—')
                 .gsub('-4712', '——')
    end

    I18n.localize(date)
  end

  # Attempt to make an I18n localization,
  # but return a localized date-string with '—' in the place of date numbers
  # and '_' in the place of time numbers
  # if no localization found
  def localize_datetime(datetime)
    if datetime.nil?
      return I18n.localize(DateTime.new)
                 .gsub('01', '—')
                 .gsub('-4712', '——')
                 .gsub(/\d/, '_')
    end

    I18n.localize(datetime)
  end

  # Attempt to make an I18n localization,
  # but return a localized date-string with '_' in the place of numbers
  # if no localization found
  def localize_time_of_day(time)
    if time.nil?
      return I18n.localize(DateTime.new)
                 .remove('01/01/-4712')
                 .strip
                 .gsub(/\d/, '_')
    end

    I18n.localize(time)
        .remove('01/01/2000')
        .strip
  end
  alias localize_time localize_time_of_day
end

app/helpers/to_html_helper.rb
# frozen_string_literal: true

require_relative './i18n_helper'

module ToHtmlHelper
  def boolean_to_html(boolean)
    content_tag(:i,
                nil,
                class: [
                  'fa',
                  (if boolean == true
                    'fa-check'
                  elsif boolean.nil?
                    'fa-minus'
                  else
                    'fa-times'
                  end),
                  (if boolean == true
                    'text-success'
                  elsif boolean.nil?
                    'text-secondary'
                  else
                    'text-danger'
                  end)
                ])
  end

  def date_to_html(date)
    return content_tag(:time, localize_date(date)) if date.nil?

    content_tag(:time,
                localize_date(date),
                datetime: date.to_formatted_s,
                'data-original-title': date.to_formatted_s(:long_ordinal))
  end

  def datetime_to_html(datetime)
    return content_tag(:time, localize_datetime(datetime)) if datetime.nil?

    content_tag(:time,
                localize_datetime(datetime),
                datetime: datetime.to_formatted_s,
                'data-original-title': datetime.to_formatted_s(:long_ordinal))
  end

  def time_of_day_to_html(time)
    return content_tag(:time, localize_time_of_day(time)) if time.nil?

    content_tag(:time,
                localize_time_of_day(time),
                datetime: time.to_formatted_s(:time))
  end
  alias time_to_html time_of_day_to_html

  def month_year_to_html(month_year)
    return content_tag(:time, localize_date(month_year)) if month_year.nil?

    content_tag(:time,
                month_year.strftime('%Y-%m'),
                datetime: month_year.to_formatted_s,
                'data-toggle': 'tooltip',
                'title': month_year.strftime('%B %Y'))
  end

  def fullname_to_html(first:, last:, middle: nil)
    content_tag(:span, class: 'fullname') do
      safe_join([
                  content_tag(:span, first, class: 'firstname'),
                  content_tag(:span, last, class: 'lastname'),
                  (content_tag(:span, middle, class: 'middlename') if middle)
                ])
    end
  end
end

app/views/comic_characters/_form.html.erb
<%= form_with(model: comic_character, local: true) do |form| %>
  <% if comic_character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comic_character.errors.count, "error") %> prohibited this comic_character from being saved:</h2>

      <ul>
      <% comic_character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :universe %>
    <%= form.text_field :universe %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :appearances %>
    <%= form.number_field :appearances %>
  </div>

  <div class="field">
    <%= form.label :alive %>
    <%= form.check_box :alive %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :eye %>
    <%= form.text_field :eye %>
  </div>

  <div class="field">
    <%= form.label :hair %>
    <%= form.text_field :hair %>
  </div>

  <div class="field">
    <%= form.label :identity_type %>
    <%= form.text_field :identity_type %>
  </div>

  <div class="field">
    <%= form.label :alignment %>
    <%= form.text_field :alignment %>
  </div>

  <div class="field">
    <%= form.label :intro_on %>
    <%= form.date_select :intro_on %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comic_characters/edit.html.erb
<h1>Editing Comic Character</h1>

<%= render 'form', comic_character: @comic_character %>

<%= link_to 'Show', @comic_character %> |
<%= link_to 'Back', comic_characters_path %>

app/views/comic_characters/new.html.erb
<h1>New Comic Character</h1>

<%= render 'form', comic_character: @comic_character %>

<%= link_to 'Back', comic_characters_path %>

app/views/comic_characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Universe:</strong>
  <%= @comic_character.universe %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comic_character.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @comic_character.url %>
</p>

<p>
  <strong>Appearances:</strong>
  <%= @comic_character.appearances %>
</p>

<p>
  <strong>Alive:</strong>
  <%= @comic_character.alive %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @comic_character.gender %>
</p>

<p>
  <strong>Eye:</strong>
  <%= @comic_character.eye %>
</p>

<p>
  <strong>Hair:</strong>
  <%= @comic_character.hair %>
</p>

<p>
  <strong>Identity type:</strong>
  <%= @comic_character.identity_type %>
</p>

<p>
  <strong>Alignment:</strong>
  <%= @comic_character.alignment %>
</p>

<p>
  <strong>Intro on:</strong>
  <%= @comic_character.intro_on %>
</p>

<%= link_to 'Edit', edit_comic_character_path(@comic_character) %> |
<%= link_to 'Back', comic_characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avengers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/powertable/_columnheader.html.erb
<%# parameters:
  attribute String (required)
  label String (required)
  attributes Hash (optional)
%>

<%
  def current_sort_direction_for(attribute:)
    if sort_params.key?(:attribute) && sort_params.key?(:direction) && sort_params[:attribute] == attribute.to_s
      sort_params[:direction]
    else
      sort_params[attribute]
    end
  end

  def next_sort_direction_for(attribute:)
    next_sort_direction_mapping = {
      'ascending' => 'descending',
      'descending' => 'ascending',
      'asc' => 'descending',
      'desc' => 'ascending',
      nil => 'ascending'
    }

    next_sort_direction_mapping[current_sort_direction_for(attribute: attribute)]
  end

  def aria_sort_direction_for(attribute:)
    aria_sort_direction_mapping = {
      'ascending' => 'ascending',
      'descending' => 'descending',
      'asc' => 'ascending',
      'desc' => 'descending',
      nil => 'none'
    }

    aria_sort_direction_mapping[current_sort_direction_for(attribute: attribute)]
  end

  default_attributes = {
    role: 'columnheader',
    scope: 'col',
    'aria-sort': aria_sort_direction_for(attribute: attribute),
  }
  attributes ||= { class: 'text-left' }
%>

<%= content_tag(:th, default_attributes.merge(attributes)) do %>
  <%= link_to(url_for(sort: { attribute => next_sort_direction_for(attribute: attribute) }),
              'aria-label': "sort by '#{ attribute }' in #{ next_sort_direction_for(attribute: attribute) } order") do %>
    <small class="text-uppercase font-weight-bold">
      <%= label %>
    </small>
  <% end %>
<% end %>